export const SELECT_BOOK = "SELECT_BOOK";
export type SELECT_BOOK = typeof SELECT_BOOK;

export const CONTINUTE_NEXT = "CONTINUTE_NEXT";
export type CONTINUTE_NEXT = typeof CONTINUTE_NEXT;

export const FETCH_NEXT_REQUEST = "FETCH_NEXT_REQUEST";
export type FETCH_NEXT_REQUEST = typeof FETCH_NEXT_REQUEST;

export const FETCH_NEXT_SUCCESSS = "FETCH_NEXT_SUCCESSS";
export type FETCH_NEXT_SUCCESSS = typeof FETCH_NEXT_SUCCESSS;

export const FETCH_NEXT_FAILURE = "FETCH_NEXT_FAILURE";
export type FETCH_NEXT_FAILURE = typeof FETCH_NEXT_FAILURE;

export const FETCH_PERCENTAGE_REPORT = "FETCH_PERCENTAGE_REPORT";
export type FETCH_PERCENTAGE_REPORT = typeof FETCH_PERCENTAGE_REPORT;